"""Database and key-related concepts."""

from lecture2graph.plugins.base import DomainPlugin, PrerequisiteRule


PLUGIN = DomainPlugin(
    name="databases",
    concept_patterns={
        "primary key": [r"primary\s+key"],
        "candidate key": [r"candidate\s+key"],
        "super key": [r"super\s+key"],
        "foreign key": [r"foreign\s+key"],
        "composite key": [r"composite\s+key"],
        "alternate key": [r"alternate\s+key", r"alternative\s+key"],
        "unique constraint": [r"\bunique\b"],
        "not null": [r"not\s+null"],
        "null": [r"\bnull\b"],
        "attribute": [r"\battribute\b", r"\battributes\b", r"\bcolumn\b", r"\bcolumns\b"],
        "tuple": [r"\btuple\b", r"\btuples\b", r"\brow\b(?!\s+level)"],
        "relation": [r"\brelation\b", r"\btable\b(?!\s+of\s+contents)"],
        "database": [r"\bdatabase\b", r"\bdbms\b", r"\brdbms\b"],
        "normalization": [r"\bnormali[sz]ation\b", r"\bnormal\s+form\b"],
        "functional dependency": [r"functional\s+depend", r"\bfd\b"],
        "schema": [r"\bschema\b"],
        "entity": [r"\bentity\b", r"\bentities\b"],
        "index": [r"\bindex\b(?!\.)", r"\bindexing\b"],
        "sql": [r"\bsql\b", r"\bsequel\b"],
        "constraint": [r"\bconstraint\b", r"\bconstraints\b"],
    },
    ocr_keywords={
        "primary": "primary key",
        "primary key": "primary key",
        "candidate": "candidate key",
        "candidate key": "candidate key",
        "super key": "super key",
        "foreign": "foreign key",
        "foreign key": "foreign key",
        "unique": "unique constraint",
        "null": "null",
        "not null": "not null",
        "attribute": "attribute",
        "tuple": "tuple",
        "table": "relation",
        "relation": "relation",
        "schema": "schema",
        "sql": "sql",
        "normalization": "normalization",
        "index": "index",
        "constraint": "constraint",
    },
    prerequisite_rules=[
        PrerequisiteRule("database", "relation", reason="Relations are foundational units inside a relational database."),
        PrerequisiteRule("relation", "attribute", confidence=0.8, reason="Attributes are properties of a relation."),
        PrerequisiteRule("relation", "tuple", confidence=0.8, reason="Tuples are rows inside a relation."),
        PrerequisiteRule("attribute", "candidate key", confidence=0.8, reason="Keys are defined over attributes."),
        PrerequisiteRule("attribute", "super key", confidence=0.8, reason="Super keys are defined over attributes."),
        PrerequisiteRule("unique constraint", "candidate key", confidence=0.8, reason="Candidate keys must enforce uniqueness."),
        PrerequisiteRule("not null", "primary key", confidence=0.8, reason="Primary keys cannot be null."),
        PrerequisiteRule("null", "not null", confidence=0.7, reason="The lecture contrasts null values with not-null constraints."),
        PrerequisiteRule("candidate key", "primary key", reason="A primary key is chosen from candidate keys."),
        PrerequisiteRule("candidate key", "alternate key", confidence=0.8, reason="Alternate keys are candidate keys not selected as primary."),
        PrerequisiteRule("super key", "candidate key", relation="refines", confidence=0.85, reason="Candidate keys are minimal super keys."),
        PrerequisiteRule("primary key", "foreign key", confidence=0.85, reason="Foreign keys reference a primary key."),
        PrerequisiteRule("primary key", "composite key", confidence=0.7, reason="Composite primary keys extend the idea of a primary key."),
        PrerequisiteRule("unique constraint", "primary key", confidence=0.8, reason="Primary keys inherit uniqueness requirements."),
        PrerequisiteRule("constraint", "unique constraint", relation="refines", confidence=0.7, reason="A unique constraint is a specific constraint."),
        PrerequisiteRule("constraint", "not null", relation="refines", confidence=0.7, reason="Not-null is a specific constraint."),
        PrerequisiteRule("relation", "normalization", confidence=0.8, reason="Normalization operates on relations and schemas."),
        PrerequisiteRule("functional dependency", "normalization", confidence=0.8, reason="Normalization depends on functional dependencies."),
        PrerequisiteRule("primary key", "normalization", confidence=0.7, reason="Primary keys matter for higher normal forms."),
        PrerequisiteRule("attribute", "functional dependency", confidence=0.7, reason="Functional dependencies describe relationships between attributes."),
        PrerequisiteRule("database", "sql", confidence=0.8, reason="SQL is introduced in the context of relational databases."),
        PrerequisiteRule("relation", "sql", confidence=0.7, reason="SQL queries operate over relations."),
        PrerequisiteRule("database", "schema", confidence=0.8, reason="Schemas describe database structure."),
        PrerequisiteRule("entity", "relation", confidence=0.7, reason="Entities are mapped into relations."),
    ],
    fragment_aliases={
        "primary key": "primary key",
        "candidate key": "candidate key",
        "super key": "super key",
        "foreign key": "foreign key",
        "composite key": "composite key",
        "alternate key": "alternate key",
        "unique": "unique constraint",
        "not null": "not null",
        "null": "null",
        "attribute": "attribute",
        "column": "attribute",
        "tuple": "tuple",
        "row": "tuple",
        "relation": "relation",
        "table": "relation",
        "database": "database",
        "dbms": "database",
        "normalization": "normalization",
        "functional dependency": "functional dependency",
        "schema": "schema",
        "entity": "entity",
        "sql": "sql",
        "sequel": "sql",
        "constraint": "constraint",
        "index": "index",
    },
    descriptions={
        "database": "An organized system for storing and retrieving structured data.",
        "relation": "A table-like structure in the relational model.",
        "attribute": "A column or property in a relation.",
        "tuple": "A single row or record in a relation.",
        "candidate key": "A minimal set of attributes that uniquely identifies each tuple.",
        "primary key": "The chosen candidate key used as the main identifier for rows.",
        "super key": "Any set of attributes that uniquely identifies a row, minimal or not.",
        "foreign key": "An attribute that references a key in another relation.",
        "composite key": "A key formed from more than one attribute.",
        "alternate key": "A candidate key not selected as the primary key.",
        "unique constraint": "A rule that prevents duplicate values in one or more columns.",
        "not null": "A constraint that forbids missing values.",
        "null": "A marker representing missing or unknown data.",
        "schema": "The structural blueprint of a database.",
        "normalization": "A design process that reduces redundancy and anomalies in relational schemas.",
        "functional dependency": "A relationship where one set of attributes determines another.",
        "entity": "A real-world object or concept modeled in a database.",
        "index": "A structure that speeds up lookup operations.",
        "sql": "The standard query language used to work with relational databases.",
        "constraint": "A rule enforced by the database to protect data integrity.",
    },
)

