"""Graph, BFS, and DFS concepts."""

from lecture2graph.plugins.base import DomainPlugin, PrerequisiteRule


PLUGIN = DomainPlugin(
    name="graphs",
    concept_patterns={
        "breadth first search": [r"\bbfs\b", r"breadth\s+first\s+search", r"breadth\s+first"],
        "depth first search": [r"\bdfs\b", r"depth\s+first\s+search", r"depth\s+first"],
        "graph traversal": [r"graph\s+travers", r"travers(?:e|ing|al)\s+(?:a\s+)?graph"],
        "graph": [r"\bgraph\b", r"\bgraphs\b"],
        "vertex": [r"\bvertex\b", r"\bvertices\b", r"\bvertice\b"],
        "edge": [r"\bedge\b", r"\bedges\b"],
        "queue": [r"\bqueue\b", r"\bfifo\b"],
        "stack": [r"\bstack\b", r"\blifo\b"],
        "visited": [r"\bvisited\b", r"visit(?:ed)?\s+(?:array|list|set|node)"],
        "adjacency list": [r"adjacen(?:cy|t)\s+(?:list|matrix)", r"adjacen(?:cy|t)\b"],
        "connected component": [r"connected\s+component"],
        "shortest path": [r"shortest\s+path", r"shortest\s+distance"],
        "level order": [r"level\s+(?:order|by\s+level|wise)"],
    },
    ocr_keywords={
        "bfs": "breadth first search",
        "dfs": "depth first search",
        "queue": "queue",
        "stack": "stack",
        "visited": "visited",
        "graph": "graph",
        "vertex": "vertex",
        "edge": "edge",
        "adjacency": "adjacency list",
    },
    prerequisite_rules=[
        PrerequisiteRule("graph", "graph traversal", reason="Traversal builds on understanding what a graph is."),
        PrerequisiteRule("vertex", "graph", confidence=0.7, reason="Graphs are defined in terms of vertices."),
        PrerequisiteRule("edge", "graph", confidence=0.7, reason="Graphs are defined in terms of edges."),
        PrerequisiteRule("graph traversal", "breadth first search", relation="refines", reason="BFS is a graph traversal method."),
        PrerequisiteRule("graph traversal", "depth first search", relation="refines", reason="DFS is a graph traversal method."),
        PrerequisiteRule("graph", "breadth first search", reason="BFS is taught over graphs."),
        PrerequisiteRule("graph", "depth first search", reason="DFS is taught over graphs."),
        PrerequisiteRule("queue", "breadth first search", reason="BFS relies on a queue frontier."),
        PrerequisiteRule("stack", "depth first search", reason="DFS relies on stack behavior, explicit or implicit."),
        PrerequisiteRule("visited", "breadth first search", confidence=0.7, reason="BFS needs visited-state tracking."),
        PrerequisiteRule("visited", "depth first search", confidence=0.7, reason="DFS needs visited-state tracking."),
        PrerequisiteRule("adjacency list", "breadth first search", confidence=0.6, reason="BFS iterates neighbors from a graph representation."),
        PrerequisiteRule("adjacency list", "depth first search", confidence=0.6, reason="DFS iterates neighbors from a graph representation."),
        PrerequisiteRule("node", "vertex", confidence=0.5, reason="The lecture often bridges from node language to vertex language."),
        PrerequisiteRule("breadth first search", "shortest path", confidence=0.7, reason="BFS is commonly used to explain shortest paths in unweighted graphs."),
        PrerequisiteRule("connected component", "graph traversal", confidence=0.6, reason="Traversals are used to find connected components."),
    ],
    fragment_aliases={
        "breadth first search": "breadth first search",
        "breadth first": "breadth first search",
        "bfs": "breadth first search",
        "depth first search": "depth first search",
        "depth first": "depth first search",
        "dfs": "depth first search",
        "graph traversal": "graph traversal",
        "graph": "graph",
        "vertex": "vertex",
        "edge": "edge",
        "queue": "queue",
        "stack": "stack",
        "visited": "visited",
        "adjacency": "adjacency list",
        "shortest path": "shortest path",
    },
    descriptions={
        "graph": "A data structure made of vertices connected by edges.",
        "vertex": "A single node in a graph.",
        "edge": "A connection between two vertices in a graph.",
        "graph traversal": "A method for systematically visiting nodes in a graph.",
        "breadth first search": "A traversal that explores neighbors level by level using a queue.",
        "depth first search": "A traversal that goes as deep as possible before backtracking.",
        "queue": "A first-in, first-out data structure.",
        "stack": "A last-in, first-out data structure.",
        "visited": "A record of nodes already explored during traversal.",
        "adjacency list": "A graph representation storing each vertex and its neighbors.",
        "connected component": "A subset of graph vertices where every pair is reachable.",
        "shortest path": "The minimum-cost or minimum-step route between two nodes.",
        "level order": "A traversal order that processes nodes by distance or level.",
    },
)

