"""Tree and traversal concepts."""

from lecture2graph.plugins.base import DomainPlugin, PrerequisiteRule


PLUGIN = DomainPlugin(
    name="trees",
    concept_patterns={
        "tree traversal": [r"tree\s+traversal", r"traversal\s+technique"],
        "pre-order traversal": [r"pre[\-\s]?order", r"preorder"],
        "in-order traversal": [r"in[\-\s]?order", r"inorder"],
        "post-order traversal": [r"post[\-\s]?order", r"postorder"],
        "binary tree": [r"binary\s+tree"],
        "root node": [r"root\s+node", r"root\s+element", r"\broot\b"],
        "leaf node": [r"leaf\s+node", r"leaf\b"],
        "left subtree": [r"left\s+(?:subtree|child|node|element|side)"],
        "right subtree": [r"right\s+(?:subtree|child|node|element|side)"],
        "node": [r"\bnode\b", r"\bnodes\b"],
        "tree": [r"\btree\b"],
        "children": [r"\bchildren\b", r"\bchild\b"],
        "dummy node": [r"dummy\b"],
        "traversal technique": [r"technique\b", r"traversing\b"],
    },
    ocr_keywords={
        "root": "root node",
        "left": "left subtree",
        "right": "right subtree",
        "preorder": "pre-order traversal",
        "inorder": "in-order traversal",
        "post": "post-order traversal",
        "postorder": "post-order traversal",
        "node": "node",
    },
    prerequisite_rules=[
        PrerequisiteRule("tree", "binary tree", reason="Binary trees are a specialized type of tree."),
        PrerequisiteRule("tree", "tree traversal", reason="Traversal builds on the basic idea of a tree."),
        PrerequisiteRule("binary tree", "tree traversal", reason="The lecture traverses a binary tree example."),
        PrerequisiteRule("node", "root node", reason="A root node is a specific kind of node."),
        PrerequisiteRule("node", "leaf node", reason="Leaf nodes are defined as nodes with no children."),
        PrerequisiteRule("root node", "tree traversal", reason="Traversal order is explained relative to the root."),
        PrerequisiteRule("children", "left subtree", confidence=0.7, reason="Subtrees are explained through child relationships."),
        PrerequisiteRule("children", "right subtree", confidence=0.7, reason="Subtrees are explained through child relationships."),
        PrerequisiteRule("tree traversal", "pre-order traversal", relation="refines", reason="Pre-order is one traversal strategy."),
        PrerequisiteRule("tree traversal", "in-order traversal", relation="refines", reason="In-order is one traversal strategy."),
        PrerequisiteRule("tree traversal", "post-order traversal", relation="refines", reason="Post-order is one traversal strategy."),
        PrerequisiteRule("traversal technique", "pre-order traversal", confidence=0.7, reason="Pre-order is taught as a traversal technique."),
        PrerequisiteRule("traversal technique", "in-order traversal", confidence=0.7, reason="In-order is taught as a traversal technique."),
        PrerequisiteRule("traversal technique", "post-order traversal", confidence=0.7, reason="Post-order is taught as a traversal technique."),
        PrerequisiteRule("left subtree", "pre-order traversal", confidence=0.7, reason="Pre-order depends on how the left subtree is visited."),
        PrerequisiteRule("right subtree", "pre-order traversal", confidence=0.7, reason="Pre-order depends on how the right subtree is visited."),
        PrerequisiteRule("left subtree", "in-order traversal", confidence=0.7, reason="In-order depends on how the left subtree is visited."),
        PrerequisiteRule("right subtree", "in-order traversal", confidence=0.7, reason="In-order depends on how the right subtree is visited."),
        PrerequisiteRule("left subtree", "post-order traversal", confidence=0.7, reason="Post-order depends on how the left subtree is visited."),
        PrerequisiteRule("right subtree", "post-order traversal", confidence=0.7, reason="Post-order depends on how the right subtree is visited."),
        PrerequisiteRule("dummy node", "traversal technique", relation="part_of", confidence=0.6, reason="Dummy nodes appear as part of the traversal illustration."),
    ],
    fragment_aliases={
        "pre-order": "pre-order traversal",
        "preorder": "pre-order traversal",
        "pre order": "pre-order traversal",
        "in-order": "in-order traversal",
        "inorder": "in-order traversal",
        "in order": "in-order traversal",
        "post-order": "post-order traversal",
        "postorder": "post-order traversal",
        "post order": "post-order traversal",
        "root node": "root node",
        "root": "root node",
        "left": "left subtree",
        "right": "right subtree",
        "tree": "tree",
        "node": "node",
        "leaf": "leaf node",
        "binary tree": "binary tree",
        "children": "children",
        "child": "children",
    },
    descriptions={
        "tree": "A hierarchical data structure made of connected nodes.",
        "node": "A single element in a tree or graph structure.",
        "root node": "The topmost node from which the tree starts.",
        "leaf node": "A node with no children.",
        "left subtree": "The subtree reachable through the left child of a node.",
        "right subtree": "The subtree reachable through the right child of a node.",
        "tree traversal": "A strategy for visiting every node in a tree in a specific order.",
        "pre-order traversal": "Visit the root first, then the left subtree, then the right subtree.",
        "in-order traversal": "Visit the left subtree, then the root, then the right subtree.",
        "post-order traversal": "Visit the left subtree, then the right subtree, then the root.",
        "binary tree": "A tree where each node has at most two children.",
        "children": "Nodes directly below a parent node.",
        "traversal technique": "A general method for visiting nodes in a data structure.",
        "dummy node": "An example or placeholder node used to illustrate a traversal rule.",
    },
)

